### PR TITLE
Update video_extras_tab.py

### PR DESCRIPTION
**Pull request by D0n-A**
Good day! It's a mini-fix for that:
```
...\modules\gradio_extensons.py:25: GradioUnusedKwargWarning: You have unused kwarg parameters in Textbox, please remove them: {'maxlines': 10000}
  res = original_IOComponent_init(self, *args, **kwargs)
```
Although this is not a very necessary thing, so far we have not heard about updating SD (and, accordingly, Gradio), so...

### CODE REVIEW

**Comment by light-and-ray** [comment]
What do you mean by "updating sd"? I know gradio has been updated, and if automatic1111 will use the newest version almost every extension will be broken, and I will fix it

**Comment by light-and-ray** [comment]
Sorry but I don't merge 1-line PRs. (There are a lot of statistics spammers) Also as I remember there was a restriction of maximum of lines that I need to bypass

**Comment by D0n-A** [comment]
Repository Stable Diffusion (SD - I shortened it like this) unknown when it will be updated (there have been no updates since July; same as Gradio in "SD") for ordinary users (not developers or etc.)
The error (kwargs) is displayed when the setting is enabled: "Show gradio deprecation warnings in console."
About "1-line PR "- I didn't know - but at least it would be nice to have a look at the changes (1 line - due to which the warning is displayed.)

Request suggested instead of creating issue.
Thanks for the answer. Sorry to take up your time.

**Comment by light-and-ray** [comment]
Maybe you're right and this argument doesn't exist in this gradio version. I'm not sure that I'd faced with a limit with no this argument. But I'm not sure is it really need to be fixed

> Repository Stable Diffusion (SD - I shortened it like this) unknown

Hmm I've seen something about this in the devs' discord. Unfortunately Automatic doesn't answer and doesn't review PRs for a few months :(

**Pull request closed without merging**
